server:
  port: 8083
spring:
  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:${CLASSPATH}
        project-id: ${PROJECT_ID}
        bucket: ${BUCKET_KEY}

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/one-team-SA-proj
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
custom:
  genFileDirPath: C:\work_oneteam\one-team-SA-proj
