server:
  port: 8088

spring:
  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:${CLASSPATH}
        project-id: ${PROJECT_ID}
        bucket: ${BUCKET_KEY}

  mail:
    host: smtp.gmail.com
    port: 587
    username: axdswww12@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oneteam_project?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password:

custom:
  genFileDirPath: C:\work_oneteam\one-team-SA-proj

web:
  resources:
    static-locations: classpath:/static/

mybatis:
  type-aliases-package: com.lyj.proj.vo
